<paste log output from Kubernetes-mediated prediction, here>
Error from server (AlreadyExists): pods "predictionapp" already exists
NAME            READY   STATUS    RESTARTS   AGE
predictionapp   1/1     Running   0          29s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
[2022-07-22 17:52:21,941] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-07-22 17:52:21,965] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-07-22 17:52:21,979] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-07-22 17:52:21,987] INFO in app: output prediction: 
[20.35373177134412]
127.0.0.1 - - [22/Jul/2022 17:52:21] "POST /predict HTTP/1.1" 200 -